// import { Outfit,Orbitron } from "next/font/google";
// import "./globals.css";
// import ConvexClientProvider from "./ConvexClientProvider";

// export const metadata = {
//   title: "GenVid",
//   description: "Generated by create next app",
// };

// const outfit = Outfit({ subsets: ['latin'] })

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning={true}>
//       <body
//        className={outfit.className}
//       >
//         <ConvexClientProvider>
//         {children}
//         </ConvexClientProvider>
        
//       </body>
//     </html>
//   );
// }


import { Outfit, Geist, Geist_Mono, Pixelify_Sans } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "./ConvexClientProvider";

export const metadata = {
  title: "Kwik Reels",
  description: "Generate viral short videos using AI — fast, free, and fun!",
  openGraph: {
    title: "Kwik Reels",
    description: "Generate viral short videos using AI — fast, free, and fun!",
    url: "https://kwik-reels.vercel.app",
    siteName: "Kwik Reels",
    images: [
      {
        url: "https://kwik-reels.vercel.app/preview.png", // Place preview.png in /public
        width: 1200,
        height: 630,
        alt: "Kwik Reels – AI Generated Shorts",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Kwik Reels",
    description: "Generate viral short videos using AI — fast, free, and fun!",
    images: ["https://kwik-reels.vercel.app/preview.png"],
  },
};

const outfit = Outfit({ subsets: ["latin"] });
// Landing page fonts, exposed as CSS variables (see tailwind fontFamily)
const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });
const pixelify = Pixelify_Sans({ subsets: ["latin"], variable: "--font-pixel" });

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${outfit.className} ${geistSans.variable} ${geistMono.variable} ${pixelify.variable}`}
      >
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
